### PR TITLE
SSR support idea

### PR DESCRIPTION
**Pull request by Maretzky85**
Idea for SSR problem

### CODE REVIEW

**Review by erichjsonfosse — APPROVED** [review]
Thanks @Maretzky85 !

**Comment by erichjsonfosse** [comment]
@Maretzky85 
I've published a release candidate now. Could you test it for your project, and let me know if everything works as expected? :)

**Comment by Maretzky85** [comment]
Its working for me as expected :)

**Comment by erichjsonfosse** [comment]
@Maretzky85 
Sweet! 3.1.0 is now published! Thanks for contributing :+1:

**Pull request merged**
